### ISSUE TITLE
could you help me find NaviCLI-Linux-64-x86-en_US-7.33.9.1.84-1.x86_64.rpm?

### ISSUE THREAD

**Issue by lkx007** [emc-openstack/naviseccli#1]

**Comment by Murray-LIANG** [comment]
Here you are.

[NaviCLI-Linux-64-x86-en_US-7.33.9.1.84-1.x86_64.rpm.zip](https://github.com/emc-openstack/naviseccli/files/2456335/NaviCLI-Linux-64-x86-en_US-7.33.9.1.84-1.x86_64.rpm.zip)

**Comment by lkx007** [comment]
Thanks a lot. BTW, I installed powervc-1.3.0.0 in redhat 7.2, and my cinder rpm version is shown as follows:

[root@powervc ~]# rpm -qa|grep cinder
python-cinderclient-1.3.1-1.ibm.el7.noarch
python-cinder-7.0.0-201511012019.ibm.el7.232.noarch
openstack-cinder-7.0.0-201511012019.ibm.el7.232.noarch
[root@powervc ~]# 

Then I add a emc vnx5300 to powervc , and create lun using powervc , this  NaviCLI-Linux command execute failure as '-sp' param is not set in '/opt/Navisphere/bin/naviseccli' commands as follows:


2018-10-08 18:48:25.375 2597 INFO cinder.volume.drivers.emc.emc_vnx_cli [req-4820a9bb-83c1-485a-a2aa-4f726ffec775 - - - - -] Create Volume: volume-lkx1-a76d4cd2-1631  Size: 1 pool: blue_pool provisioning: thick tiering: none snapcopy: false.
2018-10-08 18:48:25.584 2597 WARNING cinder.volume.manager [req-4820a9bb-83c1-485a-a2aa-4f726ffec775 - - - - -] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeFromSpecTask;volume:create' (41992de2-1035-4e15-8752-2eaf75e1c7fb) transitioned into state 'FAILURE' from state 'RUNNING'
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager Traceback (most recent call last):
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/taskflow/engines/action_engine/executor.py", line 67, in _execute_task
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager     result = task.execute(**arguments)
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 820, in execute
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager     **volume_spec)
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/cinder/volume/flows/manager/create_volume.py", line 798, in _create_raw_volume
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager     return self.driver.create_volume(volume_ref)
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/osprofiler/profiler.py", line 105, in wrapper
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager     return f(*args, **kwargs)
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager   File "/usr/lib/python2.7/site-packages/powervc_cinder/volume/drivers/emc/emc_vnx_product.py", line 415, in create_volume
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager     raise e
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager EMCVnxCLICmdError: CN-706D8B5 EMC VNX Cinder Driver CLI exception: ['-np', 'lun', '-create', '-capacity', 1, '-sq', 'gb', '-poolName', u'blue_pool', '-name', u'volume-lkx1-a76d4cd2-1631', '-type', 'NonThin'] (Return Code: 40) (Output: [u'Usage:\\n  storagepool -create -disks disksList -rtype raidType\\n       [-description description][-name name]\\n       [-prcntFullThreshold threshold]\\n       [-autoTiering scheduled|manual(default)]\\n       [-fastcache on|off][-skipRules]\\n  storagepool -destroy -id poolID|-name poolName [-o]\\n  storagepool -expand -id poolID |-name poolName\\n       -disks disksList [-skipRules][-o]\\n  storagepool -cancelExpand -id poolID|-name poolName\\n  storagepool -list [-id poolID |-name poolName][-availableCap]\\n       [-consumedCap][-currentOp][-description][-disks]\\n       [-diskType][-luns][-opState][-opStatus][-prcntOp][-rawCap][-rtype]\\n       [-prcntFullThreshold][-state][-status][-subscribedCap][-userCap]\\n       [-prcntFull][-autoTiering][-tiers][-fastcache][-all]\\n  storagepool -modify -id poolID|-name poolName\\n       [-description description][-newName newName]\\n       [-prcntFullThreshold threshold][-autoTiering scheduled|manual]\\n       [-fastcache on|off][-o]\\n  storagepool -feature -info [-isVirtualProvisioningSupported]\\n       [-maxPools][-maxDiskDrivesPerPool][-maxDiskDrivesAllPools]\\n       [-maxDiskDrivesPerOp][-maxPoolLUNs][-minPoolLUNSize][-maxPoolLUNSize]\\n       [-numPools][-numPoolLUNs][-numThinLUNs][-numDiskDrivesAllPools]\\n       [-availableDisks]\\n  lun -create [-type Thin|NonThin] -capacity capacity [-sq mb|gb|tb|bc]\\n       -poolId storagePoolID |-poolName storagePoolName\\n       -sp spID [-aa autoAssignment][-l lunNumber][-name lunName]\\n       [-offset logicalBlockAddress]\\n       [-tieringPolicy noMovement|autoTier|highestAvailable|lowestAvailable]\\n       [-initialTier optimizePool|highestAvailable|lowestAvailable]\\n  lun -destroy -l lunNumber|-name lunName [-o]\\n  lun -list [-l lunNumber|-name lunName]|[-showOnly Thin|NonThin|Compressed|NonCompressed][-aa]\\n       [-alOwner][-at][-userCap][-consumedCap][-default][-drivetype]\\n       [-offset][-rtype][-state][-status][-owner][-poolName][-uid]\\n       [-opDetails][-isPoolLUN][-isThinLUN][-isPrivate][-isCompressed][-featureData]\\n       [-perfData][-tieringPolicy][-initialTier][-tiers][-all]\\n  lun -modify -l lunNumber|-name lunName [-aa autoAssign]\\n       [-newName newLUNName][-sp newDefaultSPID]\\n       [-tieringPolicy noMovement|autoTier|highestAvailable|lowestAvailable]\\n       [-initialTier optimizePool|highestAvailable|lowestAvailable][-o]\\n  lun -expand -l lunNumber|-name lunName\\n       -capacity capacity [-sq mb|gb|tb|bc][-o]\\n\\nAll of the following options must be specified: (-capacity,-sp).\\n']).
2018-10-08 18:48:25.584 2597 ERROR cinder.volume.manager

I presume that if the version of NaviCLI-Linux and powervc version do not match at all, any suggestions?

**Comment by Murray-LIANG** [comment]
Seems a bug in powervc_cinder. It wrote `-capacity` and `-sp` are required options to create luns. The `-capacity` was passed in, but `-sp` didn't.

**Comment by lkx007** [comment]
Could u please help me find another powervc installation package to avoid this, I only found powervc-install-x86-rhel-1.3.0.0.tgz

**Comment by Murray-LIANG** [comment]
We doesn't maintain the powervc. You need to contact with the guys who maintain it.

**Comment by lkx007** [comment]
Thank you very much.
